jobs:
  build:
    docker:
      - image: 'circleci/node:12.9.1-browsers'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Run lints
          command: npm run lint
      - run:
          name: Run tests with updated snapshots
          command: npm run test -u
      - run:
          name: Install api
          command: npm --prefix ./api install
      - run:
          name: Lint api
          command: npm --prefix ./api run prebuild
      - run:
          name: test api
          command: npm --prefix ./api run test
